services:
  hs110:
    image: jaydenk/hs110exporter
    container_name: hs110exporter
    restart: unless-stopped
    environment:
      - HS110IP=hs110sim
      - FREQUENCY=1
      - LISTENPORT=8110
      - LABEL=location=home
    ports:
      - 8110:8110


