services:
  hs110:
    image: tilt.dev/hs110-exporter
    depends_on: [ hs110sim ]
    build: .
    environment:
      - HS110IP=hs110sim
      - FREQUENCY=1
      - LISTENPORT=8110
     - LABEL=location=home
   ports:
     - 8110:8110


